version: "3"

services:

  postgres:
    image: "kartoza/postgis:11.0-2.5"
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
        POSTGRES_PASSWORD: "searchlocation"
        POSTGRES_USER: "searchlocation"
        POSTGRES_DB: "searchlocation" 
    volumes:
        - "./db:/db"     

  api:
    image: "dmelosilva/search-location"
    hostname: api
    build: .
    environment:
      WAIT_HOSTS: postgres:5432
      DB_HOST: "postgres"
      DB_DATABASE: "searchlocation"
      DB_USER: "searchlocation"
      DB_PASSWORD: "searchlocation"
      DB_PORT: "5432"
    ports:
        - 3030:3030
        - 9221:9221  
    